[workspace]
members = ["sitemap_rs"]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2024"
rust-version = "1.89"
authors = ["Todd Everett Griffin <tgriffin115@gmail.com>"]
readme = "README.md"
repository = "https://github.com/goddtriffin/sitemap-rs"
homepage = "https://www.toddgriffin.me/"
description = "A Rust library to generate URL, Index, Image, Video, and News sitemaps."
license = "MIT"
keywords = [
  "sitemap",
  "index-sitemap",
  "image-sitemap",
  "video-sitemap",
  "news-sitemap",
]
categories = ["web-programming", "parsing"]
include = ["**/*.rs", "Cargo.toml", ".clippy.toml", "LICENSE", "README.md"]

[workspace.lints.rust]
unsafe_code = { level = "forbid", priority = 0 }
unfulfilled_lint_expectations = { level = "forbid", priority = 1 }

[workspace.lints.clippy]
allow_attributes = { level = "forbid", priority = 1 }
nursery = { level = "allow", priority = 0 }
all = { level = "deny", priority = -1 }
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }

[workspace.dependencies]
xml-builder = "0.6.0"
chrono = "0.4.41"

# benchmarks
criterion = "0.8.2"
dhat = "0.3.3"
